service: "ops-backoffice-sabinov"

image: "sd/ops-backoffice-sabinov"

servers:
  web:
    hosts:
      - 88.99.99.215

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: sabinov.odkazprestarostu.sk

env: &sabinov_env
  clear:
    SERVICE_NAME: ops-backoffice-sabinov
    FQDN: sabinov.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-sabinov-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-sabinov
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-sabinov
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Sabinov
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 4
    OPS_RESPONSIBLE_SUBJECT: Sabinov
    OPS_RESPONSIBLE_SUBJECT_ID: 218

    NOTIFICATION_SENDER: "Sabinov | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-sabinov@odkazprestarostu.sk

    POSTGRESQL_USER: ops_backoffice_sabinov
    POSTGRESQL_DB: ops_backoffice_sabinov_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

accessories:
  railsserver: &accessory-hack
    image: "sd/ops-backoffice-sabinov:<%= `git rev-parse HEAD`.strip %>"
    volumes:
      - "ops-backoffice-sabinov-storage:/opt/zammad/storage"
    env:
      <<: *sabinov_env
    cmd: "zammad-railsserver"

  websocket:
    <<: *accessory-hack
    cmd: "zammad-websocket"

volumes:
  - "ops-backoffice-sabinov-storage:/opt/zammad/storage"
