service: "ops-backoffice-novemesto-ba"

image: "sd/ops-backoffice-novemesto-ba"

servers:
  web:
    hosts:
      - novemesto-ba.ops.dev.slovensko.digital
    proxy:
      host: novemesto-ba.ops.dev.slovensko.digital
    options:
      memory: 1.5g

  websocket:
    hosts:
      - novemesto-ba.ops.dev.slovensko.digital

  worker:
    hosts:
      - novemesto-ba.ops.dev.slovensko.digital

proxy:
  host: novemesto-ba.ops.dev.slovensko.digital

env:
  clear:
    SERVICE_NAME: ops-backoffice-novemesto-ba
    FQDN: novemesto-ba.ops.dev.slovensko.digital
    REDIS_URL: "redis://ops-backoffice-novemesto-ba-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-novemesto-ba
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-novemesto-ba
    OPS_CONNECTOR_URL: https://ops.dev.slovensko.digital
    OPS_PORTAL_URL: https://ops.dev.slovensko.digital
    ORGANIZATION: Bratislava - Nové Mesto
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 8
    OPS_RESPONSIBLE_SUBJECT: MÚ Nové Mesto
    OPS_RESPONSIBLE_SUBJECT_ID: 5

    NOTIFICATION_SENDER: "DEV | Nové Mesto | Backoffice"
    NOTIFICATION_SMTP_USER: noreply-novemesto-ba@ops.dev.slovensko.digital

    POSTGRESQL_USER: ops_backoffice_novemesto_ba
    POSTGRESQL_DB: ops_backoffice_novemesto_ba_staging
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

volumes:
  - "ops-backoffice-novemesto-ba-storage:/opt/zammad/storage"
