service: "ops-backoffice-malacky"

image: "sd/ops-backoffice-malacky"

servers:
  web:
    hosts:
      - 88.99.99.215

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: malacky.odkazprestarostu.sk

env: &malacky_env
  clear:
    SERVICE_NAME: ops-backoffice-malacky
    FQDN: malacky.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-malacky-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-malacky
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-malacky
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Malacky
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 1
    OPS_RESPONSIBLE_SUBJECT: Malacky
    OPS_RESPONSIBLE_SUBJECT_ID: 119

    POSTGRESQL_USER: ops_backoffice_malacky
    POSTGRESQL_DB: ops_backoffice_malacky_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

accessories:
  railsserver: &accessory-hack
    image: "sd/ops-backoffice-malacky:<%= `git rev-parse HEAD`.strip %>"
    volumes:
      - "ops-backoffice-malacky-storage:/opt/zammad/storage"
    env:
      <<: *malacky_env
    cmd: "zammad-railsserver"

  websocket:
    <<: *accessory-hack
    cmd: "zammad-websocket"

volumes:
  - "ops-backoffice-malacky-storage:/opt/zammad/storage"
