service: "ops-backoffice-modra"

image: "sd/ops-backoffice-modra"

servers:
  web:
    hosts:
      - 88.99.99.215
    proxy:
      host: modra.odkazprestarostu.sk
    options:
      memory: 1.5g

  websocket:
    hosts:
      - 88.99.99.215

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: modra.odkazprestarostu.sk

env:
  clear:
    SERVICE_NAME: ops-backoffice-modra
    FQDN: modra.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-modra-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-modra
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-modra
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Modra
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 2
    OPS_RESPONSIBLE_SUBJECT: Modra
    OPS_RESPONSIBLE_SUBJECT_ID: 59

    NOTIFICATION_SENDER: "Modra | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-modra@odkazprestarostu.sk

    POSTGRESQL_USER: ops_backoffice_modra
    POSTGRESQL_DB: ops_backoffice_modra_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

volumes:
  - "ops-backoffice-modra-storage:/opt/zammad/storage"
