service: "ops-backoffice-hlohovec"

image: "sd/ops-backoffice-hlohovec"

servers:
  web:
    hosts:
      - hlohovec.odkazprestarostu.sk
    proxy:
      host: hlohovec.odkazprestarostu.sk
    options:
      memory: 1.5g

  websocket:
    hosts:
      - hlohovec.odkazprestarostu.sk

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: hlohovec.odkazprestarostu.sk

env:
  clear:
    SERVICE_NAME: ops-backoffice-hlohovec
    FQDN: hlohovec.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-hlohovec-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-hlohovec
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-hlohovec
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Hlohovec
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 3
    OPS_RESPONSIBLE_SUBJECT: Hlohovec
    OPS_RESPONSIBLE_SUBJECT_ID: 44

    NOTIFICATION_SENDER: "Hlohovec | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-hlohovec@odkazprestarostu.sk

    POSTGRESQL_USER: ops_backoffice_hlohovec
    POSTGRESQL_DB: ops_backoffice_hlohovec_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

volumes:
  - "ops-backoffice-hlohovec-storage:/opt/zammad/storage"
