service: "ops-backoffice-dolnykubin"

image: "sd/ops-backoffice-dolnykubin"

servers:
  web:
    hosts:
      - 88.99.99.215

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: dolnykubin.odkazprestarostu.sk

env: &dolnykubin_env
  clear:
    SERVICE_NAME: ops-backoffice-dolnykubin
    FQDN: dolnykubin.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-dolnykubin-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-dolnykubin
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-dolnykubin
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Dolný Kubín
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 9
    OPS_RESPONSIBLE_SUBJECT: Dolný Kubín
    OPS_RESPONSIBLE_SUBJECT_ID: 175

    NOTIFICATION_SENDER: "Dolný Kubín | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-dolnykubin@odkazprestarostu.sk

    POSTGRESQL_USER: ops_backoffice_dolnykubin
    POSTGRESQL_DB: ops_backoffice_dolnykubin_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

accessories:
  railsserver: &accessory-hack
    image: "sd/ops-backoffice-dolnykubin:<%= `git rev-parse HEAD`.strip %>"
    volumes:
      - "ops-backoffice-dolnykubin-storage:/opt/zammad/storage"
    env:
      <<: *dolnykubin_env
    cmd: "zammad-railsserver"

  websocket:
    <<: *accessory-hack
    cmd: "zammad-websocket"

volumes:
  - "ops-backoffice-dolnykubin-storage:/opt/zammad/storage"
