service: "ops-backoffice-stupava"

image: "sd/ops-backoffice-stupava"

servers:
  web:
    hosts:
      - stupava.ops.dev.slovensko.digital
    proxy:
      host: stupava.ops.dev.slovensko.digital
    options:
      memory: 1.5g

  websocket:
    hosts:
      - stupava.ops.dev.slovensko.digital

  worker:
    hosts:
      - stupava.ops.dev.slovensko.digital

proxy:
  host: stupava.ops.dev.slovensko.digital

env:
  clear:
    SERVICE_NAME: ops-backoffice-stupava
    FQDN: stupava.ops.dev.slovensko.digital
    REDIS_URL: "redis://ops-backoffice-stupava-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-stupava
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-stupava
    OPS_CONNECTOR_URL: https://ops.dev.slovensko.digital
    OPS_PORTAL_URL: https://ops.dev.slovensko.digital
    ORGANIZATION: Stupava
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 6
    OPS_RESPONSIBLE_SUBJECT: MÃš Stupava
    OPS_RESPONSIBLE_SUBJECT_ID: 148

    NOTIFICATION_SENDER: "DEV | Stupava | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-stupava@ops.dev.slovensko.digital

    POSTGRESQL_USER: ops_backoffice_stupava
    POSTGRESQL_DB: ops_backoffice_stupava_staging
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

volumes:
  - "ops-backoffice-stupava-storage:/opt/zammad/storage"
