service: "ops-backoffice-prievidza"

image: "sd/ops-backoffice-prievidza"

servers:
  web:
    hosts:
      - 88.99.99.215

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: prievidza.odkazprestarostu.sk

env: &prievidza_env
  clear:
    SERVICE_NAME: ops-backoffice-prievidza
    FQDN: prievidza.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-prievidza-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-prievidza
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-prievidza
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Prievidza
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 10
    OPS_RESPONSIBLE_SUBJECT: MÃš Prievidza
    OPS_RESPONSIBLE_SUBJECT_ID: 39

    NOTIFICATION_SENDER: "Prievidza | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-prievidza@odkazprestarostu.sk

    POSTGRESQL_USER: ops_backoffice_prievidza
    POSTGRESQL_DB: ops_backoffice_prievidza_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

accessories:
  railsserver: &accessory-hack
    image: "sd/ops-backoffice-prievidza:<%= `git rev-parse HEAD`.strip %>"
    volumes:
      - "ops-backoffice-prievidza-storage:/opt/zammad/storage"
    env:
      <<: *prievidza_env
    cmd: "zammad-railsserver"

  websocket:
    <<: *accessory-hack
    cmd: "zammad-websocket"

volumes:
  - "ops-backoffice-prievidza-storage:/opt/zammad/storage"
