service: "ops-backoffice-sabinov"

image: "sd/ops-backoffice-sabinov"

servers:
  web:
    hosts:
      - 195.201.202.110
    proxy:
      host: sabinov.odkazprestarostu.sk
    options:
      memory: 1.5g

  websocket:
    hosts:
      - 195.201.202.110

  worker:
    hosts:
      - 195.201.202.110

proxy:
  host: sabinov.odkazprestarostu.sk

env:
  clear:
    SERVICE_NAME: ops-backoffice-sabinov
    FQDN: sabinov.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-sabinov-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-sabinov
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-sabinov
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Sabinov
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 4
    OPS_RESPONSIBLE_SUBJECT: Sabinov
    OPS_RESPONSIBLE_SUBJECT_ID: 218

    NOTIFICATION_SENDER: "Sabinov | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-sabinov@odkazprestarostu.sk

    POSTGRESQL_USER: ops_backoffice_sabinov
    POSTGRESQL_DB: ops_backoffice_sabinov_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

volumes:
  - "ops-backoffice-sabinov-storage:/opt/zammad/storage"
