service: "ops-backoffice-trnava"

image: "sd/ops-backoffice-trnava"

servers:
  web:
    hosts:
      - 88.99.99.215

  worker:
    hosts:
      - 88.99.99.215

proxy:
  host: trnava.odkazprestarostu.sk

env: &trnava_env
  clear:
    SERVICE_NAME: ops-backoffice-trnava
    FQDN: trnava.odkazprestarostu.sk
    REDIS_URL: "redis://ops-backoffice-trnava-redis:6379/1"
    ELASTICSEARCH_NAMESPACE: ops-backoffice-zammad-trnava
    ZAMMAD_ELASTICSEARCH_USER: ops-backoffice-zammad-trnava
    OPS_CONNECTOR_URL: https://novy.odkazprestarostu.sk
    OPS_PORTAL_URL: https://novy.odkazprestarostu.sk
    ORGANIZATION: Trnava
    PRODUCT_NAME: Backoffice
    WEBHOOK_TENANT_ID: 11
    OPS_RESPONSIBLE_SUBJECT: Trnava
    OPS_RESPONSIBLE_SUBJECT_ID: 23

    NOTIFICATION_SENDER: "Trnava | Backoffice"
    NOTIFICATION_SMTP_USER: notifikacie-trnava@odkazprestarostu.sk

    POSTGRESQL_USER: ops_backoffice_trnava
    POSTGRESQL_DB: ops_backoffice_trnava_production
    POSTGRESQL_HOST: host.docker.internal
    POSTGRESQL_OPTIONS: "?pool=50"

accessories:
  railsserver: &accessory-hack
    image: "sd/ops-backoffice-trnava:<%= `git rev-parse HEAD`.strip %>"
    volumes:
      - "ops-backoffice-trnava-storage:/opt/zammad/storage"
    env:
      <<: *trnava_env
    cmd: "zammad-railsserver"

  websocket:
    <<: *accessory-hack
    cmd: "zammad-websocket"

volumes:
  - "ops-backoffice-trnava-storage:/opt/zammad/storage"
