name: DEV All Deployments

on:
  workflow_dispatch:

jobs:
  dev_magistrat_ba:
    uses: ./.github/workflows/dev_magistrat_ba_deploy.yml
    secrets: inherit

  dev_stupava:
    needs: dev_magistrat_ba
    if: ${{ always() }}
    uses: ./.github/workflows/dev_stupava_deploy.yml
    secrets: inherit

  dev_malacky:
    needs: dev_stupava
    if: ${{ always() }}
    uses: ./.github/workflows/dev_malacky_deploy.yml
    secrets: inherit

  dev_staremesto_ba:
    needs: dev_malacky
    if: ${{ always() }}
    uses: ./.github/workflows/dev_staremesto_ba_deploy.yml
    secrets: inherit
