name: PROD Batch B Deployments

on:
  workflow_dispatch:

jobs:
  prod_malacky:
    uses: ./.github/workflows/prod_malacky_deploy.yml

  prod_modra:
    uses: ./.github/workflows/prod_modra_deploy.yml

  prod_sabinov:
    uses: ./.github/workflows/prod_sabinov_deploy.yml

  prod_banska_bystrica:
    uses: ./.github/workflows/prod_banska_bystrica_deploy.yml

  prod_hlohovec:
    uses: ./.github/workflows/prod_hlohovec_deploy.yml
